export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXT_PUBLIC_URL = process.env.NEXT_PUBLIC_URL;
export const NEXT_PUBLIC_TOKEN_EXPIRE_IN_MINS =
  process.env.NEXT_PUBLIC_TOKEN_EXPIRE_IN_MINS;
export const NEXT_PUBLIC_TOKEN_REFRESH_IN_MINUTES =
  process.env.NEXT_PUBLIC_TOKEN_REFRESH_IN_MINUTES;
